sudo: required
services:
  - docker
  
 before_install:
      - docker build -t gdaoud/docker-react -f Dockerfile.dev .

script
      - docker run -e CI=true gdaoud/docker-react npm run test -- --coverage